# Generated by Django 4.2.7 on 2023-11-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
