# Generated by Django 4.2.7 on 2023-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
