# Generated by Django 4.2.7 on 2023-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminventory',
            options={'verbose_name_plural': 'Item Inventories'},
        ),
        migrations.RenameField(
            model_name='iteminventory',
            old_name='damage_amount_gram',
            new_name='damage_quantity',
        ),
        migrations.RenameField(
            model_name='iteminventory',
            old_name='stock_in_gram',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram')], default='piece', max_length=10),
        ),
    ]
