# Generated by Django 4.2.7 on 2023-12-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_alter_iteminventory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_code',
        ),
        migrations.AddField(
            model_name='item',
            name='variant',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='damage_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'KG')], default='piece', max_length=10),
        ),
    ]
