# Generated by Django 4.2.7 on 2023-12-03 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0003_remove_item_item_code_item_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='variant',
            field=models.CharField(default='Deshi', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='UsageInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('using_date', models.DateField(default=datetime.date.today)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_inventory', to='InventoryApp.item')),
            ],
        ),
    ]
