# Generated by Django 4.2.7 on 2023-12-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_alter_item_variant_alter_iteminventory_purchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminventory',
            name='unit',
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'KG')], default='piece', max_length=10),
        ),
    ]
