# Generated by Django 4.2.7 on 2023-12-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0005_remove_iteminventory_unit_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='variant',
            field=models.CharField(default='Deshi', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('item_name', 'variant')},
        ),
    ]
