# Generated by Django 4.2.7 on 2023-12-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0006_alter_item_variant_alter_item_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('product_list', models.JSONField()),
                ('Billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('po_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Piece'), ('kg', 'KG')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='damage_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
