# Generated by Django 4.2.7 on 2023-12-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0007_invoice_alter_item_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventory',
            name='Invoice_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_no', to='InventoryApp.invoice'),
        ),
    ]
