# Generated by Django 4.2.7 on 2023-12-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0009_alter_iteminventory_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
