# Generated by Django 4.2.7 on 2023-12-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0010_alter_invoice_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
