# Generated by Django 4.2.7 on 2023-12-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0012_alter_invoice_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='subtotal',
            new_name='totalAmount',
        ),
    ]
