# Generated by Django 4.2.7 on 2023-11-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealhistory',
            old_name='user',
            new_name='user_id',
        ),
    ]
