# Generated by Django 4.2.7 on 2023-11-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0002_rename_user_mealhistory_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
