# Generated by Django 4.2.7 on 2023-11-09 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HostelApp', '0003_rename_user_id_mealhistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazarHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_bazar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bazar_details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bazar_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
