# Generated by Django 4.2.7 on 2023-11-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0004_bazarhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bazarhistory',
            old_name='daily_bazar',
            new_name='daily_bazar_cost',
        ),
    ]
